title: Divya Vellanki # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Hello, I am Divya . I have 6 years of demonstrated experience in enterprise architecture and analytics. Motivated by the belief that there is always something to learn and do things in a new way. I am focused on expanding horizons in the machine learning community as a contributor through continuous learning.
  <br><br>
  
Core Competencies:

  - ETL - Informatica, Mulesoft, Dell Boomi
  - Machine Learning , Statistics, Deep Learning
  - Data Visualization - Tableau, Dash
  - Languages - Python , Scala , Java, Spring Boot
  - Statistical Software â€“ SAS, R, Excel
  - Scripting - Unix
  - Platforms - Kubernetes , Docker, Kubeflow
  - Front-end - Java Script, Angular 
  <br><br>
  <a href="https://www.linkedin.com/in/divya-vellanki/">View My LinkedIn Profile</a> 
 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
